//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 19/9/2014 10:38:27 AM
namespace WebApp.MembersService
{
    
    /// <summary>
    /// There are no comments for MemberEntities in the schema.
    /// </summary>
    public partial class MemberEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new MemberEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MemberEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "RESOServices", "WebApp.MembersService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WebApp.MembersService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("RESOServices.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for MEMBER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MEMBER> MEMBER
        {
            get
            {
                if ((this._MEMBER == null))
                {
                    this._MEMBER = base.CreateQuery<MEMBER>("MEMBER");
                }
                return this._MEMBER;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MEMBER> _MEMBER;
        /// <summary>
        /// There are no comments for MEMBER_OUTPUT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MEMBER_OUTPUT> MEMBER_OUTPUT
        {
            get
            {
                if ((this._MEMBER_OUTPUT == null))
                {
                    this._MEMBER_OUTPUT = base.CreateQuery<MEMBER_OUTPUT>("MEMBER_OUTPUT");
                }
                return this._MEMBER_OUTPUT;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MEMBER_OUTPUT> _MEMBER_OUTPUT;
        /// <summary>
        /// There are no comments for MEMBER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMEMBER(MEMBER mEMBER)
        {
            base.AddObject("MEMBER", mEMBER);
        }
        /// <summary>
        /// There are no comments for MEMBER_OUTPUT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMEMBER_OUTPUT(MEMBER_OUTPUT mEMBER_OUTPUT)
        {
            base.AddObject("MEMBER_OUTPUT", mEMBER_OUTPUT);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"RESOServices\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><E" +
                "ntityType Name=\"MEMBER\"><Key><PropertyRef Name=\"MemberKey\" /></Key><Property Nam" +
                "e=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xml" +
                "ns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name" +
                "=\"MemberKey\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"fals" +
                "e\" Unicode=\"false\" /><Property Name=\"OriginatingSystemMemberKey\" Type=\"Edm.Strin" +
                "g\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"Originat" +
                "ingSystemName\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"fal" +
                "se\" /><Property Name=\"MemberMlsId\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=" +
                "\"false\" Unicode=\"false\" /><Property Name=\"MemberFullName\" Type=\"Edm.String\" MaxL" +
                "ength=\"150\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"MemberPreferre" +
                "dPhone\" Type=\"Edm.String\" MaxLength=\"16\" FixedLength=\"false\" Unicode=\"false\" /><" +
                "Property Name=\"MemberOfficePhone\" Type=\"Edm.String\" MaxLength=\"16\" FixedLength=\"" +
                "false\" Unicode=\"false\" /><Property Name=\"MemberCellPhone\" Type=\"Edm.String\" MaxL" +
                "ength=\"16\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"MemberFax\" Type" +
                "=\"Edm.String\" MaxLength=\"16\" FixedLength=\"false\" Unicode=\"false\" /><Property Nam" +
                "e=\"MemberPager\" Type=\"Edm.String\" MaxLength=\"16\" FixedLength=\"false\" Unicode=\"fa" +
                "lse\" /><Property Name=\"MemberEmail\" Type=\"Edm.String\" MaxLength=\"80\" FixedLength" +
                "=\"false\" Unicode=\"false\" /><Property Name=\"MemberURL\" Type=\"Edm.String\" MaxLengt" +
                "h=\"8000\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"MemberStateLicens" +
                "e\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"false\" /></Enti" +
                "tyType><EntityType Name=\"MEMBER_OUTPUT\"><Key><PropertyRef Name=\"ProcessDateTime\"" +
                " /></Key><Property Name=\"StatusCode\" Type=\"Edm.String\" MaxLength=\"10\" FixedLengt" +
                "h=\"false\" Unicode=\"false\" /><Property Name=\"TotalFound\" Type=\"Edm.Int32\" /><Prop" +
                "erty Name=\"ProcessDateTime\" Type=\"Edm.DateTime\" Nullable=\"false\" Precision=\"3\" /" +
                "><Property Name=\"Details\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" " +
                "Unicode=\"true\" /></EntityType></Schema><Schema Namespace=\"RESOServices.Models\" x" +
                "mlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"Membe" +
                "rEntities\" m:IsDefaultEntityContainer=\"true\" p6:LazyLoadingEnabled=\"true\" xmlns:" +
                "p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\"><EntitySet Name=\"ME" +
                "MBER\" EntityType=\"RESOServices.MEMBER\" /><EntitySet Name=\"MEMBER_OUTPUT\" EntityT" +
                "ype=\"RESOServices.MEMBER_OUTPUT\" /><FunctionImport Name=\"Member\" ReturnType=\"Col" +
                "lection(RESOServices.MEMBER)\" EntitySet=\"MEMBER\" m:HttpMethod=\"GET\"><Parameter N" +
                "ame=\"Id\" Type=\"Edm.String\" /></FunctionImport></EntityContainer></Schema></edmx:" +
                "DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for RESOServices.MEMBER in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MemberKey
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("MemberKey")]
    public partial class MEMBER
    {
        /// <summary>
        /// Create a new MEMBER object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="memberKey">Initial value of MemberKey.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MEMBER CreateMEMBER(int ID, string memberKey)
        {
            MEMBER mEMBER = new MEMBER();
            mEMBER.Id = ID;
            mEMBER.MemberKey = memberKey;
            return mEMBER;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property MemberKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MemberKey
        {
            get
            {
                return this._MemberKey;
            }
            set
            {
                this.OnMemberKeyChanging(value);
                this._MemberKey = value;
                this.OnMemberKeyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MemberKey;
        partial void OnMemberKeyChanging(string value);
        partial void OnMemberKeyChanged();
        /// <summary>
        /// There are no comments for Property OriginatingSystemMemberKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OriginatingSystemMemberKey
        {
            get
            {
                return this._OriginatingSystemMemberKey;
            }
            set
            {
                this.OnOriginatingSystemMemberKeyChanging(value);
                this._OriginatingSystemMemberKey = value;
                this.OnOriginatingSystemMemberKeyChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OriginatingSystemMemberKey;
        partial void OnOriginatingSystemMemberKeyChanging(string value);
        partial void OnOriginatingSystemMemberKeyChanged();
        /// <summary>
        /// There are no comments for Property OriginatingSystemName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OriginatingSystemName
        {
            get
            {
                return this._OriginatingSystemName;
            }
            set
            {
                this.OnOriginatingSystemNameChanging(value);
                this._OriginatingSystemName = value;
                this.OnOriginatingSystemNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OriginatingSystemName;
        partial void OnOriginatingSystemNameChanging(string value);
        partial void OnOriginatingSystemNameChanged();
        /// <summary>
        /// There are no comments for Property MemberMlsId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MemberMlsId
        {
            get
            {
                return this._MemberMlsId;
            }
            set
            {
                this.OnMemberMlsIdChanging(value);
                this._MemberMlsId = value;
                this.OnMemberMlsIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MemberMlsId;
        partial void OnMemberMlsIdChanging(string value);
        partial void OnMemberMlsIdChanged();
        /// <summary>
        /// There are no comments for Property MemberFullName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MemberFullName
        {
            get
            {
                return this._MemberFullName;
            }
            set
            {
                this.OnMemberFullNameChanging(value);
                this._MemberFullName = value;
                this.OnMemberFullNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MemberFullName;
        partial void OnMemberFullNameChanging(string value);
        partial void OnMemberFullNameChanged();
        /// <summary>
        /// There are no comments for Property MemberPreferredPhone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MemberPreferredPhone
        {
            get
            {
                return this._MemberPreferredPhone;
            }
            set
            {
                this.OnMemberPreferredPhoneChanging(value);
                this._MemberPreferredPhone = value;
                this.OnMemberPreferredPhoneChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MemberPreferredPhone;
        partial void OnMemberPreferredPhoneChanging(string value);
        partial void OnMemberPreferredPhoneChanged();
        /// <summary>
        /// There are no comments for Property MemberOfficePhone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MemberOfficePhone
        {
            get
            {
                return this._MemberOfficePhone;
            }
            set
            {
                this.OnMemberOfficePhoneChanging(value);
                this._MemberOfficePhone = value;
                this.OnMemberOfficePhoneChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MemberOfficePhone;
        partial void OnMemberOfficePhoneChanging(string value);
        partial void OnMemberOfficePhoneChanged();
        /// <summary>
        /// There are no comments for Property MemberCellPhone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MemberCellPhone
        {
            get
            {
                return this._MemberCellPhone;
            }
            set
            {
                this.OnMemberCellPhoneChanging(value);
                this._MemberCellPhone = value;
                this.OnMemberCellPhoneChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MemberCellPhone;
        partial void OnMemberCellPhoneChanging(string value);
        partial void OnMemberCellPhoneChanged();
        /// <summary>
        /// There are no comments for Property MemberFax in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MemberFax
        {
            get
            {
                return this._MemberFax;
            }
            set
            {
                this.OnMemberFaxChanging(value);
                this._MemberFax = value;
                this.OnMemberFaxChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MemberFax;
        partial void OnMemberFaxChanging(string value);
        partial void OnMemberFaxChanged();
        /// <summary>
        /// There are no comments for Property MemberPager in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MemberPager
        {
            get
            {
                return this._MemberPager;
            }
            set
            {
                this.OnMemberPagerChanging(value);
                this._MemberPager = value;
                this.OnMemberPagerChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MemberPager;
        partial void OnMemberPagerChanging(string value);
        partial void OnMemberPagerChanged();
        /// <summary>
        /// There are no comments for Property MemberEmail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MemberEmail
        {
            get
            {
                return this._MemberEmail;
            }
            set
            {
                this.OnMemberEmailChanging(value);
                this._MemberEmail = value;
                this.OnMemberEmailChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MemberEmail;
        partial void OnMemberEmailChanging(string value);
        partial void OnMemberEmailChanged();
        /// <summary>
        /// There are no comments for Property MemberURL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MemberURL
        {
            get
            {
                return this._MemberURL;
            }
            set
            {
                this.OnMemberURLChanging(value);
                this._MemberURL = value;
                this.OnMemberURLChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MemberURL;
        partial void OnMemberURLChanging(string value);
        partial void OnMemberURLChanged();
        /// <summary>
        /// There are no comments for Property MemberStateLicense in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MemberStateLicense
        {
            get
            {
                return this._MemberStateLicense;
            }
            set
            {
                this.OnMemberStateLicenseChanging(value);
                this._MemberStateLicense = value;
                this.OnMemberStateLicenseChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MemberStateLicense;
        partial void OnMemberStateLicenseChanging(string value);
        partial void OnMemberStateLicenseChanged();
    }
    /// <summary>
    /// There are no comments for RESOServices.MEMBER_OUTPUT in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProcessDateTime
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProcessDateTime")]
    public partial class MEMBER_OUTPUT
    {
        /// <summary>
        /// Create a new MEMBER_OUTPUT object.
        /// </summary>
        /// <param name="processDateTime">Initial value of ProcessDateTime.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MEMBER_OUTPUT CreateMEMBER_OUTPUT(global::System.DateTime processDateTime)
        {
            MEMBER_OUTPUT mEMBER_OUTPUT = new MEMBER_OUTPUT();
            mEMBER_OUTPUT.ProcessDateTime = processDateTime;
            return mEMBER_OUTPUT;
        }
        /// <summary>
        /// There are no comments for Property StatusCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string StatusCode
        {
            get
            {
                return this._StatusCode;
            }
            set
            {
                this.OnStatusCodeChanging(value);
                this._StatusCode = value;
                this.OnStatusCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _StatusCode;
        partial void OnStatusCodeChanging(string value);
        partial void OnStatusCodeChanged();
        /// <summary>
        /// There are no comments for Property TotalFound in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> TotalFound
        {
            get
            {
                return this._TotalFound;
            }
            set
            {
                this.OnTotalFoundChanging(value);
                this._TotalFound = value;
                this.OnTotalFoundChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _TotalFound;
        partial void OnTotalFoundChanging(global::System.Nullable<int> value);
        partial void OnTotalFoundChanged();
        /// <summary>
        /// There are no comments for Property ProcessDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ProcessDateTime
        {
            get
            {
                return this._ProcessDateTime;
            }
            set
            {
                this.OnProcessDateTimeChanging(value);
                this._ProcessDateTime = value;
                this.OnProcessDateTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ProcessDateTime;
        partial void OnProcessDateTimeChanging(global::System.DateTime value);
        partial void OnProcessDateTimeChanged();
        /// <summary>
        /// There are no comments for Property Details in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Details
        {
            get
            {
                return this._Details;
            }
            set
            {
                this.OnDetailsChanging(value);
                this._Details = value;
                this.OnDetailsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Details;
        partial void OnDetailsChanging(string value);
        partial void OnDetailsChanged();
    }
}
