//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 19/9/2014 10:37:29 AM
namespace WebApp.SecurityService
{
    
    /// <summary>
    /// There are no comments for SecurityEntities in the schema.
    /// </summary>
    public partial class SecurityEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new SecurityEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SecurityEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "RESOServicesModel", "WebApp.SecurityService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WebApp.SecurityService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("RESOServicesModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for MESSAGE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MESSAGE> MESSAGE
        {
            get
            {
                if ((this._MESSAGE == null))
                {
                    this._MESSAGE = base.CreateQuery<MESSAGE>("MESSAGE");
                }
                return this._MESSAGE;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MESSAGE> _MESSAGE;
        /// <summary>
        /// There are no comments for RESULT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RESULT> RESULT
        {
            get
            {
                if ((this._RESULT == null))
                {
                    this._RESULT = base.CreateQuery<RESULT>("RESULT");
                }
                return this._RESULT;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RESULT> _RESULT;
        /// <summary>
        /// There are no comments for MESSAGE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMESSAGE(MESSAGE mESSAGE)
        {
            base.AddObject("MESSAGE", mESSAGE);
        }
        /// <summary>
        /// There are no comments for RESULT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRESULT(RESULT rESULT)
        {
            base.AddObject("RESULT", rESULT);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"RESOServicesModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/ed" +
                "m\"><EntityType Name=\"MESSAGE\"><Key><PropertyRef Name=\"Status_Code\" /></Key><Prop" +
                "erty Name=\"Status_Code\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"10\" FixedL" +
                "ength=\"false\" Unicode=\"false\" /><Property Name=\"Short_Description\" Type=\"Edm.Str" +
                "ing\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"false\" /><Prop" +
                "erty Name=\"Long_Description\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"100\" " +
                "FixedLength=\"false\" Unicode=\"false\" /></EntityType><EntityType Name=\"RESULT\"><Ke" +
                "y><PropertyRef Name=\"ProcessDateTime\" /></Key><Property Name=\"StatusCode\" Type=\"" +
                "Edm.String\" MaxLength=\"10\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=" +
                "\"TotalFound\" Type=\"Edm.Int32\" /><Property Name=\"ProcessDateTime\" Type=\"Edm.DateT" +
                "ime\" Nullable=\"false\" Precision=\"3\" /><Property Name=\"Details\" Type=\"Edm.String\"" +
                " MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /></EntityType></Schema><Sch" +
                "ema Namespace=\"RESOServices.Models\" xmlns=\"http://schemas.microsoft.com/ado/2009" +
                "/11/edm\"><EntityContainer Name=\"SecurityEntities\" m:IsDefaultEntityContainer=\"tr" +
                "ue\" p6:LazyLoadingEnabled=\"true\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009" +
                "/02/edm/annotation\"><EntitySet Name=\"MESSAGE\" EntityType=\"RESOServicesModel.MESS" +
                "AGE\" /><EntitySet Name=\"RESULT\" EntityType=\"RESOServicesModel.RESULT\" /><Functio" +
                "nImport Name=\"ApplicationToken\" ReturnType=\"Collection(RESOServicesModel.RESULT)" +
                "\" EntitySet=\"RESULT\" m:HttpMethod=\"GET\" /></EntityContainer></Schema></edmx:Data" +
                "Services></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for RESOServicesModel.MESSAGE in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Status_Code
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Status_Code")]
    public partial class MESSAGE
    {
        /// <summary>
        /// Create a new MESSAGE object.
        /// </summary>
        /// <param name="status_Code">Initial value of Status_Code.</param>
        /// <param name="short_Description">Initial value of Short_Description.</param>
        /// <param name="long_Description">Initial value of Long_Description.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MESSAGE CreateMESSAGE(string status_Code, string short_Description, string long_Description)
        {
            MESSAGE mESSAGE = new MESSAGE();
            mESSAGE.Status_Code = status_Code;
            mESSAGE.Short_Description = short_Description;
            mESSAGE.Long_Description = long_Description;
            return mESSAGE;
        }
        /// <summary>
        /// There are no comments for Property Status_Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Status_Code
        {
            get
            {
                return this._Status_Code;
            }
            set
            {
                this.OnStatus_CodeChanging(value);
                this._Status_Code = value;
                this.OnStatus_CodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Status_Code;
        partial void OnStatus_CodeChanging(string value);
        partial void OnStatus_CodeChanged();
        /// <summary>
        /// There are no comments for Property Short_Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Short_Description
        {
            get
            {
                return this._Short_Description;
            }
            set
            {
                this.OnShort_DescriptionChanging(value);
                this._Short_Description = value;
                this.OnShort_DescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Short_Description;
        partial void OnShort_DescriptionChanging(string value);
        partial void OnShort_DescriptionChanged();
        /// <summary>
        /// There are no comments for Property Long_Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Long_Description
        {
            get
            {
                return this._Long_Description;
            }
            set
            {
                this.OnLong_DescriptionChanging(value);
                this._Long_Description = value;
                this.OnLong_DescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Long_Description;
        partial void OnLong_DescriptionChanging(string value);
        partial void OnLong_DescriptionChanged();
    }
    /// <summary>
    /// There are no comments for RESOServicesModel.RESULT in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProcessDateTime
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProcessDateTime")]
    public partial class RESULT
    {
        /// <summary>
        /// Create a new RESULT object.
        /// </summary>
        /// <param name="processDateTime">Initial value of ProcessDateTime.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RESULT CreateRESULT(global::System.DateTime processDateTime)
        {
            RESULT rESULT = new RESULT();
            rESULT.ProcessDateTime = processDateTime;
            return rESULT;
        }
        /// <summary>
        /// There are no comments for Property StatusCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string StatusCode
        {
            get
            {
                return this._StatusCode;
            }
            set
            {
                this.OnStatusCodeChanging(value);
                this._StatusCode = value;
                this.OnStatusCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _StatusCode;
        partial void OnStatusCodeChanging(string value);
        partial void OnStatusCodeChanged();
        /// <summary>
        /// There are no comments for Property TotalFound in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> TotalFound
        {
            get
            {
                return this._TotalFound;
            }
            set
            {
                this.OnTotalFoundChanging(value);
                this._TotalFound = value;
                this.OnTotalFoundChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _TotalFound;
        partial void OnTotalFoundChanging(global::System.Nullable<int> value);
        partial void OnTotalFoundChanged();
        /// <summary>
        /// There are no comments for Property ProcessDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ProcessDateTime
        {
            get
            {
                return this._ProcessDateTime;
            }
            set
            {
                this.OnProcessDateTimeChanging(value);
                this._ProcessDateTime = value;
                this.OnProcessDateTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ProcessDateTime;
        partial void OnProcessDateTimeChanging(global::System.DateTime value);
        partial void OnProcessDateTimeChanged();
        /// <summary>
        /// There are no comments for Property Details in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Details
        {
            get
            {
                return this._Details;
            }
            set
            {
                this.OnDetailsChanging(value);
                this._Details = value;
                this.OnDetailsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Details;
        partial void OnDetailsChanging(string value);
        partial void OnDetailsChanged();
    }
}
